### ISSUE TITLE
Error on import of plugin due to change in saleor

### ISSUE THREAD

**Issue by toastedtoast** [carlosa54/saleor-flat-tax-plugin#3]
Hi,

first, thanks for creating this plugin. 
Saleor just released v3.3 and this breaks your plugin unfortunately. At least the import of the ErrorsCodes.

They updated the vatlayer plugin in this [commit](https://github.com/saleor/saleor/commit/efd87586f5dd809cc5b1bbdb01c561033451ec36#diff-f13c61498641742b6a8476ef0bf500828a21ac5bad033589f82db61396c78240R22).

It looks as if they just moved the ErrorCodes

`from ...graphql.core.utils.error_codes import PluginErrorCode` becomes `from ...plugins.error_codes import PluginErrorCode`

Not quite sure if that has any additional effect on your code but maybe you want to have a look at it?

Kind regards,
Marco

**Comment by carlosa54** [comment]
Hi Marco,

Thanks for bringing this up, I still haven't got the chance to update my saleor repo to the latest version hence why I haven't needed to update this repo with the breaking change.

Looks like I need to do some small changes, I think I'll have time over the weekend to open up a PR.

As an FYI Saleor is working on a more robust way of handling dynamic taxes in this [PR](https://github.com/saleor/saleor/pull/9526). After that's done I think that there won't be a need for this repo/plugin anymore.

**Comment by carlosa54** [comment]
@toastedtoast this has been fixed [here](https://github.com/carlosa54/saleor-flat-tax-plugin/releases/tag/v0.4.0) and published to pypi.

Thanks for reporting 😃

**Comment by toastedtoast** [comment]
You're great. 
Yeah the whole tax stuff is kind of complicated in saleor while I only need 2 taxes in Germany and I totally struggle with the concept of why I need an API to fetch the 'latest' taxes. 

Let's see how that evolves but for now it's just great to have your super simple solution 🙏
